server:
  port: 9082

spring:
  application:
    name:  EXAMPLES-SPRINGBOOT
    description: 微服务消费用例
    version: 1.0.0-SNAPSHOT

eureka:
   instance:
#      ip-address: ${spring.cloud.client.ip-address}
     # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
      prefer-ip-address: false
      #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）_开发配置
      lease-renewal-interval-in-seconds: 5
      #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）_开发配置
      lease-expiration-duration-in-seconds: 10
#      instance-id: ${spring.cloud.client.ip-address}:${server.port}
      instance-id: ${spring.application.name}:${random.int[1,9]}
   client:
     healthcheck:
       enabled: true
     service-url:
       defaultZone: http://localhost:8761/eureka/
     register-with-eureka: true
     fetch-registry: true
     # 是否启用Eureka
     enabled: true
     registry-fetch-interval-seconds: 10

#actuator info
info:
   app:
     name:  ${spring.application.name}
     description: ${spring.application.description}
     version: ${spring.application.version}
     ip: ${spring.cloud.client.ip-address}
     port: ${server.port}

service:
  rpc:
    filter: true
  cache:
    enable: true
    timeout: 2000
    capacity: 2
  redis:
    enable: false
    ports: 6379
    hosturl: localhost
    expire: 60